# Generated by Django 4.2.5 on 2024-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Angkatan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("angkatan", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Angkatan",
                "verbose_name_plural": "Angkatan",
                "ordering": ["angkatan"],
            },
        ),
    ]
