# Generated by Django 5.1.3 on 2024-12-04 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beasiswa', '0002_prodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nim', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('angkatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='beasiswa.angkatan')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='beasiswa.prodi')),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Mahasiswa',
                'ordering': ['nim'],
            },
        ),
    ]
