# Generated by Django 5.1.3 on 2024-12-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beasiswa', '0003_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
